---
title: "Page Code Master"
author: 'DSPG: VT Page'
date: "7/27/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}

# library(tidyverse)
library (stringr)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(sf)
library(scales)
library(readxl)
library(ggmap)
library(leaflet)
library(rgdal)
library(rgeos)
library(geosphere)
library(pracma)
library(tidycensus)
library(acs)
```

## Pull ACS Data

```{r ACS Data Pull}


myACSkey <- ""
register_google(key = "")
# show available variables for ACS survey
 acs5 <- load_variables(2010, "acs5", cache=T)
 view(acs5)
 acs5<-load_variables(2018, "acs5", cache=T)
View(acs5)

acs5_subject <- load_variables(2018, "acs5/subject", cache=T)
View(acs5_subject)

acs5_profile<- load_variables(2018, "acs5/profile", cache=T)
View(acs5_profile)


# Candidate variable tables for describing poverty, educational attainment, race distribution, and housing type
# B17020 
# (001-009, 
# POVERTY STATUS IN THE PAST 12 MONTHS BY AGE, 
# Universe: Population For Whom Poverty Status Is Determined), 
# B15003 
# (001-025, 
# EDUCATIONAL ATTAINMENT FOR THE POPULATION 25 YEARS AND OVER, 
# Universe: Population 25 Years And Over), 
# B02001, B03003, B02009
# (Race/Demographics)
# B11001
# (Housing Type*)


# Create a vector of variables to pull

vars<-c(
  tot_pov_sts_12mths_age_B17020_ = "B17020_001", 
  tot_income_12mths_blw_pov_lvl_B17020_ = "B17020_002",
  tot_edu_attain_25yrs_and_up_B15003_= "B15003_001",
  tot_edu_attain_25yrs_and_up_HS_diploma_B15003_ = "B15003_017",
  tot_edu_attain_25yrs_and_up_GED_B15003_ = "B15003_018", 
  tot_edu_attain_25yrs_and_up_somecollege_freshman_B15003_ = "B15003_019", 
  tot_edu_attain_25yrs_and_up_somecollege_abovefreshman_B15003_ = "B15003_020", 
  tot_edu_attain_25yrs_and_up_assoc_B15003_= "B15003_021",
  tot_edu_attain_25yrs_and_up_bach_B15003_= "B15003_022", 
  tot_edu_attain_25yrs_and_up_masters_B15003_ = "B15003_023", 
  tot_edu_attain_25yrs_and_up_prof_degree_B15003_ = "B15003_024", 
  tot_edu_attain_25yrs_and_up_doctorate_B15003_ = "B15003_025",
  tot_race_known_ = "B02001_001",
  tot_race_black_african_american_alone_combination_ = "B02009_001",
  tot_hisp_latino_origin_known_ = "B03003_001",
  tot_hisp_latino_origin_ = "B03003_003",
  tot_employment_civil_labor_ = "B23025_003",
  tot_employment_civil_labor_employed_ = "B23025_004",
  tot_employment_civil_labor_unemployed_ = "B23025_005",
  tot_insurance_known_ = "B27001_001",
  tot_insurance_under_6yrs_without_ = "B27001_005",
  tot_insurance_6to18yrs_without_ = "B27001_008",
  tot_insurance_19to25yrs_without_ = "B27001_011",
  tot_insurance_26to34yrs_without_ = "B27001_014",
  tot_insurance_35to44yrs_without_ = "B27001_017",
  tot_insurance_45to54yrs_without_ = "B27001_020",
  tot_insurance_55to64yrs_without_ = "B27001_023",
  tot_insurance_65to74yrs_without_ = "B27001_026",
  tot_insurance_75yrs_and_up_without_ = "B27001_029",
  tot_food_assitance_known_ = "B19058_001",
  tot_food_assitance_with_ = "B19058_002",
  tot_food_assitance_without_ = "B19058_003",
  tot_vehicle_known_ = "B08014_001",
  tot_vehicle_without_ = "B08014_002",
  tot_gross_rent_known_ = "B25070_001",
  tot_gross_rent_40_to_49.9per_ = "B25070_009",
  tot_gross_rent_50per_and_up_ = "B25070_010",
  tot_gross_rent_not_computed_ = "B25070_011",
   tot_speak_spanish = "B06007_008",
   tot_speak_other_language = "B06007_005",
   tot_language = "B06007_001",
  tot_6_17_single_parent = "B05009_031",
  tot_6_single_parent = "B05009_013",
  tot_single_parent = "B05009_001",
  pov_12month_income = "B17001_002",
  tot_12month_income= "B17001_001",
  tot_male_17 = "B01001_006",
  tot_male_14 = "B01001_005",
  tot_male_9 = "B01001_004",
  tot_male_5 = "B01001_003",
  tot_pop = "B01001_001",
  tot_female_5 = "B01001_027",
  tot_female_9 = "B01001_028",
  tot_female_14 = "B01001_029",
  tot_female_17 = "B01001_030",
  tot_male_65 = "B01001_020",
  tot_male_67 = "B01001_021",
  tot_male_70 = "B01001_022",
  tot_male_75 = "B01001_023",
  tot_male_80 = "B01001_024",
  tot_male_85 = "B01001_025",
  tot_female_65 = "B01001_044",
  tot_female_67 = "B01001_045",
  tot_female_70 = "B01001_046",
  tot_female_75 = "B01001_047",
  tot_female_80 = "B01001_048",
  tot_female_85 = "B01001_049",
  tot_disability = "B18101_001",
  tot_dis_pop = "B01003_001",
  tot_group_quarters18 = "B09001_010",
  tot_group_quarters = "B26001_001"
  )
 

# Pull ACS data for VA Counties
acs_VA_CO <- get_acs(variables = vars, 
                     key = myACSkey,
                     geography = "county",
                     state = "VA",
                     survey = "acs5",
                     output = "wide",
                     show_call = T,
                     geometry = T,
                     keep_geo_vars = T,
                     year = 2018)

```

\clearpage

```{r ACS Data Manipulation}

acs_VA_CO$COUNTYFP <- as.numeric(acs_VA_CO$COUNTYFP)

# Create measures based on ACS variables


acs_VA_CO$per_black <-
  round((
    acs_VA_CO$tot_race_black_african_american_alone_combination_E / acs_VA_CO$tot_race_known_E *
      100
  ),
  2
  )
acs_VA_CO$per_hisp <-
  round((
    acs_VA_CO$tot_hisp_latino_origin_E / acs_VA_CO$tot_hisp_latino_origin_known_E *
      100
  ),
  2
  )
acs_VA_CO$per_poverty <-
  round((
    acs_VA_CO$tot_income_12mths_blw_pov_lvl_B17020_E / acs_VA_CO$tot_pov_sts_12mths_age_B17020_E *
      100
  ),
  2
  )
acs_VA_CO$per_without_hs_diploma <-
  round(((
    acs_VA_CO$tot_edu_attain_25yrs_and_up_B15003_E -
      (
        acs_VA_CO$tot_edu_attain_25yrs_and_up_HS_diploma_B15003_E +
          acs_VA_CO$tot_edu_attain_25yrs_and_up_GED_B15003_E +
          acs_VA_CO$tot_edu_attain_25yrs_and_up_somecollege_freshman_B15003_E +
          acs_VA_CO$tot_edu_attain_25yrs_and_up_somecollege_abovefreshman_B15003_E +
          acs_VA_CO$tot_edu_attain_25yrs_and_up_assoc_B15003_E +
          acs_VA_CO$tot_edu_attain_25yrs_and_up_bach_B15003_E +
          acs_VA_CO$tot_edu_attain_25yrs_and_up_masters_B15003_E +
          acs_VA_CO$tot_edu_attain_25yrs_and_up_prof_degree_B15003_E +
          acs_VA_CO$tot_edu_attain_25yrs_and_up_doctorate_B15003_E
      )
  ) /
    acs_VA_CO$tot_edu_attain_25yrs_and_up_B15003_E * 100
  ), 2)
acs_VA_CO$per_unemployed <-
  round((
    acs_VA_CO$tot_employment_civil_labor_unemployed_E / acs_VA_CO$tot_employment_civil_labor_E *
      100
  ),
  2
  )
acs_VA_CO$per_with_snap <-
  round((
    acs_VA_CO$tot_food_assitance_with_E / acs_VA_CO$tot_food_assitance_known_E *
      100
  ),
  2
  )
acs_VA_CO$per_without_vehicle <-
  round((
    acs_VA_CO$tot_vehicle_without_E / acs_VA_CO$tot_vehicle_known_E * 100
  ),
  2)
acs_VA_CO$per_without_insurance <-
  round(((
    acs_VA_CO$tot_insurance_under_6yrs_without_E +
      acs_VA_CO$tot_insurance_6to18yrs_without_E +
      acs_VA_CO$tot_insurance_19to25yrs_without_E +
      acs_VA_CO$tot_insurance_26to34yrs_without_E +
      acs_VA_CO$tot_insurance_35to44yrs_without_E +
      acs_VA_CO$tot_insurance_45to54yrs_without_E +
      acs_VA_CO$tot_insurance_55to64yrs_without_E +
      acs_VA_CO$tot_insurance_65to74yrs_without_E +
      acs_VA_CO$tot_insurance_75yrs_and_up_without_E
  ) / acs_VA_CO$tot_insurance_known_E * 100
  ), 2)
acs_VA_CO$per_gross_rent_40per_and_up <-
  round(((
    acs_VA_CO$tot_gross_rent_40_to_49.9per_E + acs_VA_CO$tot_gross_rent_50per_and_up_E
  ) /
    (
      acs_VA_CO$tot_gross_rent_known_E - acs_VA_CO$tot_gross_rent_not_computed_E
    ) * 100
  ), 2)
acs_VA_CO$language <- round((((acs_VA_CO$tot_speak_spanishE + acs_VA_CO$tot_speak_other_languageE)/acs_VA_CO$tot_languageE)*100),2)
  acs_VA_CO$per_poverty2 <- round((acs_VA_CO$pov_12month_incomeE/acs_VA_CO$tot_12month_incomeE)*100,2)
  acs_VA_CO$per_Age17 <- round(((acs_VA_CO$tot_male_5E + acs_VA_CO$tot_male_9E + acs_VA_CO$tot_male_14E + acs_VA_CO$tot_male_17E + acs_VA_CO$tot_female_5E +acs_VA_CO$tot_female_9E +acs_VA_CO$tot_female_14E + acs_VA_CO$tot_female_17E)/acs_VA_CO$tot_popE)*100, 2)
  acs_VA_CO$per_Age65 <- round(((acs_VA_CO$tot_male_65E +acs_VA_CO$tot_male_67E + acs_VA_CO$tot_male_70E +acs_VA_CO$tot_male_75E + acs_VA_CO$tot_male_80E +acs_VA_CO$tot_male_85E +
                                   acs_VA_CO$tot_female_65E + acs_VA_CO$tot_female_67E + acs_VA_CO$tot_female_70E + acs_VA_CO$tot_female_75E + acs_VA_CO$tot_female_80E +acs_VA_CO$tot_female_85E)/acs_VA_CO$tot_popE)*100, 2)
  acs_VA_CO$per_disability <- round ((acs_VA_CO$tot_disabilityE/acs_VA_CO$tot_dis_popE)*100,2)
  acs_VA_CO$per_group_quarters <- round((acs_VA_CO$tot_group_quarters18E/acs_VA_CO$tot_group_quartersE)*100,2)
  acs_VA_CO$per_sing_par <- round(((acs_VA_CO$tot_6_17_single_parentE + acs_VA_CO$tot_6_single_parentE)/acs_VA_CO$tot_single_parentE)*100,2)

```

\clearpage

```{r Virginia Education & Health Data}
# Read in data sets
businessVA_data <- read.csv("C:/Users/Admin/Documents/DSPG/Page/Virginia_Business_Data.csv", header=T,stringsAsFactors=F)
centerPop_county <- read.csv("C:/Users/Admin/Documents/DSPG/Page/Page_County_v2/data/CenPop2010_Mean_CO51.txt", header=T,stringsAsFactors=F)
map <- st_read("C:/Users/Admin/Documents/DSPG/Page/Page_County_v2/data/VirginiaShapeFiles/countylevel/SDE_USDC_CENSUS_VA_COUNTY.shp",
                stringsAsFactors = FALSE)

`%notin%` <- Negate(`%in%`)

healthVA_data <- businessVA_data %>%
  filter(X2.Digit.Title == "Health Care and Social Assistance") %>%
  filter(X3.Digit.Title %notin% c("Nursing and Residential Care Facilities")) %>%
  filter(X4.Digit.Title %notin% c("Offices of Dentists", "Home Health Care Services", "Child Day Care Services",
                                  "Continuing Care Retirement Communities and Assisted Living Facilities for the Elderly",
                                  "Individual and Family Services", "Other Residential Care Facilities",
                                  "Outpatient Care Centers", "Offices of Other Health Practitioners")) %>%
  filter(X5.Digit.Title %notin% c("Offices of Optometrists", "Offices of Chiropractors", "Community Food Services",
                                  "Community Housing Services", "Emergency and Other Relief Services", 
                                  "Offices of Physical, Occupational and Speech Therapists, and Audiologists",
                                  "Nursing Care Facilities (Skilled Nursing Facilities)", "Medical and Diagnostic Laboratories")) %>%
  filter(X6.Digit.Title %notin% c("Offices of Podiatrists", "Blood and Organ Banks",
                                  "Specialty (except Psychiatric and Substance Abuse) Hospitals"))
    

# unique(healthVA_data$X5.Digit.Title)

educationVA_data <- businessVA_data%>%
  filter(X2.Digit.Title == "Educational Services") %>%
  filter(X4.Digit.Title %notin% c("Other Schools and Instruction", "Elementary and Secondary Schools"))

# unique(educationVA_data$X4.Digit.Title)

colnames(centerPop_county)[6] <- "CENTER.LATITUDE"
colnames(centerPop_county)[7] <- "CENTER.LONGITUDE"

# Remove found duplicate entry
centerPop_county <- centerPop_county %>%
  filter(COUNTYFP != 515)


# Helper function: calculates distance in meters given 2 sets of coordinates (long, lat). 
# longitude first, then latitude
calculate_distance <- function(long1, lat1, long2, lat2){
  ans <- distm(c(long1, lat1), c(long2, lat2), fun=distHaversine)
  return(ans)
}

# Pass in location points dataset. Radius default 15 miles (in meters)
# uses county geometric center weighted by county population
loc_within_radius <- function(loc_data1, loc_data2, radius_1 = 24140.2){
  start.time <- Sys.time()
  centerData_copy <- centerPop_county
  
  centerData_copy$ED_COUNT_15mile <- NA
  centerData_copy$ED_INVERSE_DIST_15mile <- NA
  centerData_copy$HEALTH_COUNT_15mile <- NA
  centerData_copy$HEALTH_INVERSE_DIST_15mile <- NA
  
  for(i in 1:nrow(centerData_copy)){
    count_1 <- 0
    inverse_dist_1 <- 0
    count_2 <- 0
    inverse_dist_2 <- 0
    centerData_copy$ED_COUNT_15mile[i] <- 0
    centerData_copy$ED_INVERSE_DIST_15mile[i] <- 0
    centerData_copy$HEALTH_COUNT_15mile[i] <- 0
    centerData_copy$HEALTH_INVERSE_DIST_15mile[i] <- 0
    
    for(j in 1:nrow(loc_data1)){
      distance1 <- calculate_distance(centerData_copy$CENTER.LONGITUDE[i], centerData_copy$CENTER.LATITUDE[i],
                                     loc_data1$Longitude[j], loc_data1$Latitude[j])
      
      if(distance1 <= radius_1){
        count_1 <- count_1 + 1
        inverse_dist_1 <- (1/distance1) + inverse_dist_1
      }
      
    }
    centerData_copy$ED_COUNT_15mile[i] <- count_1
     if (centerData_copy$POPULATION[i] == 0) 
       centerData_copy$ED_INVERSE_DIST_15mile[i] <- NA
     else
      centerData_copy$ED_INVERSE_DIST_15mile[i] <- inverse_dist_1 / centerData_copy$POPULATION[i]
    
    for(k in 1:nrow(loc_data2)){
      distance2 <- calculate_distance(centerData_copy$CENTER.LONGITUDE[i], centerData_copy$CENTER.LATITUDE[i],
                                     loc_data2$Longitude[k], loc_data2$Latitude[k])
      
      if(distance2 <= radius_1){
        count_2 <- count_2 + 1
        inverse_dist_2 <- (1/distance2) + inverse_dist_2
      }
      
    }
    centerData_copy$HEALTH_COUNT_15mile[i] <- count_2
    if (centerData_copy$POPULATION[i] == 0)
      centerData_copy$HEALTH_INVERSE_DIST_15mile[i] <- NA
    else
      centerData_copy$HEALTH_INVERSE_DIST_15mile[i] <- inverse_dist_2 / centerData_copy$POPULATION[i]
    
  }
  stop.time <- Sys.time()
  print(loop_time <- stop.time - start.time)
  return(centerData_copy)
}

# Run time depends on data filtering
loc_data_output <- loc_within_radius(educationVA_data, healthVA_data)

map$COUNTYFP <- as.numeric(map$COUNTYFP)

# VA only
CenterPopCounty_map <- inner_join(loc_data_output, map, by="COUNTYFP")

# Check for values that did not join
anti_join(loc_data_output, map, by="COUNTYFP")
```

\clearpage

```{r Arrest Data}
# Year*
VAcounty_arrests <- read_xlsx("C:/Users/Admin/Documents/DSPG/Page/Page_County_V2/code/cleaned_arrests.xlsx", sheet = "Sheet1")

# Rename columns
VAcounty_arrests <- VAcounty_arrests %>%
  select(County, Percent, GEOID) %>%
  rename(per_substance_arrest = Percent,
         nameCounty = County)

```



\clearpage


```{r Data Merge}

loc_data_output$COUNTYFP <- as.numeric(loc_data_output$COUNTYFP)
acs_VA_CO$COUNTYFP <- as.numeric(acs_VA_CO$COUNTYFP)

# Merge Education & Health Data to Acs data
VAcounty_data_merged <- inner_join(loc_data_output, acs_VA_CO, by="COUNTYFP")


VAcounty_data_merged$GEOID <- as.numeric(VAcounty_data_merged$GEOID)
VAcounty_arrests$GEOID <- as.numeric(VAcounty_arrests$GEOID)


VAcounty_data_merged <- inner_join(VAcounty_data_merged, VAcounty_arrests, by="GEOID")
VAcounty_data_merged <- subset(VAcounty_data_merged, select = -c(nameCounty, STATEFP.y, COUNTYNS, 
                                                                 AFFGEOID, NAME.x, NAME.y, ALAND, 
                                                                 AWATER, LSAD))

# Drop Geometry column to export csv as correct format
outputCSV_data_merged <- subset(VAcounty_data_merged, select= -geometry)

 write.csv(outputCSV_data_merged, 
           "C:/Users/Admin/Documents/DSPG/Page/Page_County_V2/data\\VAcounty_data_master.csv",
          row.names = FALSE)
 
```

\clearpage


## Maps
```{r Pull Map Outlines}
va_sf <- get_acs(
  geography = "county",
  state = "VA",
  variables = "B19058_002",
  survey = "acs5",
  key = myACSkey,
  year = 2018,
  output = "wide",
  show_call = T,
  geometry = T,
  keep_geo_vars = T
) %>%
  select(COUNTYFP, geometry)


# Get Loudoun County Outline only
page_outline <- get_acs(
  geography = "county",
  state = "VA",
  county = c("Page county"),
  variables = "B19058_002",
  survey = "acs5",
  key = myACSkey,
  year = 2018,
  output = "wide",
  show_call = T,
  geometry = T,
  keep_geo_vars = T
) %>%
  select(COUNTYFP, geometry)

va_basemap <- get_map(location=c(lon = -77.5, lat = 38.8), zoom=6, scale = "auto", source = 'stamen')
```


```{r Virginia county Health Heat Map, eval = TRUE, echo=FALSE, message=FALSE, fig.height = 4, fig.width = 7, fig.align = "center"}

mypalette1 <- colorQuantile(palette="OrRd", CenterPopCounty_map$HEALTH_INVERSE_DIST_15mile,n=9)
# Health Map Inverse Distance Radius = 15 miles
ggplot(CenterPopCounty_map) + 
 geom_sf(data=CenterPopCounty_map ,aes(fill= mypalette1(HEALTH_INVERSE_DIST_15mile), geometry=geometry), inherit.aes = FALSE) +
  geom_sf(data=va_sf, fill="transparent", color="black", size=.5, inherit.aes = FALSE) +
  geom_sf(data=page_outline, fill="transparent", color="orange", size=.75, inherit.aes = FALSE) +
  scale_fill_brewer(name = "Relative Accessibility", palette = "OrRd", labels=c("High","","","","", "","","","Low")) +
  coord_sf(crs = st_crs(4326)) + theme_bw() +
  # theme(axis.line=element_blank(),axis.text.x=element_blank(),
  #       axis.text.y=element_blank(),axis.ticks=element_blank(),
  #       axis.title.x=element_blank(),
  #       axis.title.y=element_blank(),legend.position="right",
  #       panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
  #       panel.grid.minor=element_blank(),plot.background=element_blank()) +
  ggtitle("Health Care Facility Access Index (40 Miles)")
    ```

\clearpage
```{r Map tmp, eval = TRUE, echo=FALSE, message=FALSE, fig.height = 4, fig.width = 7, fig.align = "center"}
# Education Map Inverse Distance Radius = 15 miles
# Get google map background for Virginia
mypalette2 <- colorQuantile(palette="OrRd", CenterPopCounty_map$ED_INVERSE_DIST_15mile,n=9)

ggmap(va_basemap) +
  geom_sf(data=CenterPopCounty_map ,aes(fill= mypalette2(ED_INVERSE_DIST_15mile), geometry=geometry), inherit.aes = FALSE) +
  geom_sf(data=va_sf, fill="transparent", color="black", size=.5, inherit.aes = FALSE) +
  geom_sf(data=page_outline, fill="transparent", color="orange", size=.75, inherit.aes = FALSE) +
  scale_fill_brewer(name = "Relative Accessibility", palette = "OrRd", labels=c("High","","","","", "","","","Low")) +
  coord_sf(crs = st_crs(4326)) +
  theme(axis.line=element_blank(),axis.text.x=element_blank(),
        axis.text.y=element_blank(),axis.ticks=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),legend.position="right",
        panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),plot.background=element_blank()) +
  ggtitle("Educational Facility Access Index (15 Miles)") +
  ylim(-36.5,-39.5) + xlim(-84, -75) 
```

```{r Virginia County Education Heat Map, eval = TRUE, echo=FALSE, message=FALSE, fig.height = 4, fig.width = 7, fig.align = "center"}

ggplot(CenterPopCounty_map) + 
 geom_sf(data=CenterPopCounty_map ,aes(fill= mypalette2(ED_INVERSE_DIST_15mile), geometry=geometry), inherit.aes = FALSE) +
  geom_sf(data=va_sf, fill="transparent", color="black", size=.5, inherit.aes = FALSE) +
  geom_sf(data=page_outline, fill="transparent", color="orange", size=.75, inherit.aes = FALSE) +
  scale_fill_brewer(name = "Relative Accessibility", palette = "OrRd", labels=c("High","","","","", "","","","Low")) +
  coord_sf(crs = st_crs(4326)) + theme_bw() +
  # theme(axis.line=element_blank(),axis.text.x=element_blank(),
  #       axis.text.y=element_blank(),axis.ticks=element_blank(),
  #       axis.title.x=element_blank(),
  #       axis.title.y=element_blank(),legend.position="right",
  #       panel.background=element_blank(),panel.border=element_blank(),panel.grid.major=element_blank(),
  #       panel.grid.minor=element_blank(),plot.background=element_blank()) +
  ggtitle("Educational Facility Access Index (15 Miles)")
```
